version: '3'

services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: witalijkaa/laravel-mysql-php-81
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
      - appstorage:/var/www/app/storage
      - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/app
      - appstorage:/var/www/app/storage
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: mysql:8-debian
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: postgres
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  appstorage:
    driver: local
  dbdata:
    driver: local
